add_newline = true
format = "${custom.dotfile}${custom.tldr}$all"

[python]
symbol = " "
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[directory]
repo_root_style = 'bold green'
#truncation_symbol = ".../"
fish_style_pwd_dir_length = 3
read_only = ' '

[git_branch]
format = "[$symbol$branch]($style) [$remote_name]($style dimmed) "
always_show_remote = true

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_status]
ahead = "[⇡${count}](cyan)"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
#up_to_date = "[✓](green)"
modified = '[!](blue)'
staged = '[+](green)'

#untracked = "?×$count"
#stashed = "st"
#conflicted = "c"
#renamed = "r"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
disabled = false

[time]
disabled = false
format = '[\[$time\]]($style) '
style = 'cyan dimmed'

[nix_shell]
format = 'in [$symbol$state( \($name\))]($style) '
symbol = " "

[custom.dotfile]
when = """ ! ~/dotfiles/git_repo_stats.sh ~/dotfiles/"""
format = "[$symbol($output)]($style) "
description = "Symbol to warn that the dotfiles repo is not clean or fully synchronised. Use a custom script to check status of repo."
symbol = ""
style = "bold red"

[custom.tldr]
when = """ ! ~/dotfiles/git_repo_stats.sh ~/tldr/"""
format = "[$symbol($output)]($style) "
description = "Symbol to warn that the dotfiles repo is not clean or fully synchronised. Use a custom script to check status of repo."
symbol = ""
style = "bold red"

# Laptop part
[[battery.display]]
threshold = 30
