add_newline = true

[python]
format = "[$symbol$version]($style) "
symbol = " "

[directory]
repo_root_style = 'bold green'
read_only = ' '

[git_branch]
format = "[$symbol$branch]($style) [$remote_name]($style dimmed) "
always_show_remote = true

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_status]
ahead = "[⇡${count}](cyan)"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
#up_to_date = "[✓](green)"
modified = '[!](blue)'
staged = '[+](green)'

#untracked = "?×$count"
#stashed = "st"
#conflicted = "c"
#renamed = "r"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
disabled = false

[time]
disabled = false
format = '[\[$time\]]($style) '
style = 'cyan dimmed'
