[style.description]
bold = true

[style.command_name]
foreground = "red"

[style.example_text]
foreground = "green"

[style.example_code]
foreground = "cyan"

[style.example_variable]
foreground = "blue"
underline = true

[display]
compact = true
use_pager = false

[updates]
auto_update = false
